resolver: lts-7.14

packages:
- '.'

extra-deps:
- Spock-digestive-0.3.0.0
- digestive-functors-0.8.1.1
- digestive-functors-lucid-0.0.0.4
- html-email-validate-0.2.0.0

flags: {}

extra-package-dbs: []

